const body = {
  wavingHand: '👋',
  raisedBackofHand: '🤚',
  handwithFingersSplayed: '🖐',
  raisedHand: '✋',
  vulcanSalute: '🖖',
  oKHand: '👌',
  pinchingHand: '🤏',
  victoryHand: '✌',
  crossedFingers: '🤞',
  loveYouGesture: '🤟',
  signoftheHorns: '🤘',
  callMeHand: '🤙',
  backhandIndexPointingLeft: '👈',
  backhandIndexPointingRight: '👉',
  backhandIndexPointingUp: '👆',
  middleFinger: '🖕',
  backhandIndexPointingDown: '👇',
  indexPointingUp: '☝',
  thumbsUp: '👍',
  thumbsDown: '👎',
  raisedFist: '✊',
  oncomingFist: '👊',
  leftFacingFist: '🤛',
  rightFacingFist: '🤜',
  clappingHands: '👏',
  raisingHands: '🙌',
  openHands: '👐',
  palmsUpTogether: '🤲',
  handshake: '🤝',
  foldedHands: '🙏',
  writingHand: '✍',
  nailPolish: '💅',
  selfie: '🤳',
  flexedBiceps: '💪',
  mechanicalArm: '🦾',
  mechanicalLeg: '🦿',
  leg: '🦵',
  foot: '🦶',
  ear: '👂',
  earwithHearingAid: '🦻',
  nose: '👃',
  brain: '🧠',
  tooth: '🦷',
  bone: '🦴',
  eyes: '👀',
  eye: '👁',
  tongue: '👅',
  mouth: '👄',
  kissMark: '💋',
  footprints: '👣',
};

export default body;
