const clothingAndAccessories = {
  closedUmbrella: '🌂',
  umbrella: '☂',
  glasses: '👓',
  sunglasses: '🕶',
  goggles: '🥽',
  labCoat: '🥼',
  safetyVest: '🦺',
  necktie: '👔',
  tShirt: '👕',
  jeans: '👖',
  scarf: '🧣',
  gloves: '🧤',
  coat: '🧥',
  socks: '🧦',
  dress: '👗',
  kimono: '👘',
  sari: '🥻',
  onePieceSwimsuit: '🩱',
  briefs: '🩲',
  shorts: '🩳',
  bikini: '👙',
  womansClothes: '👚',
  purse: '👛',
  handbag: '👜',
  clutchBag: '👝',
  backpack: '🎒',
  mansShoe: '👞',
  runningShoe: '👟',
  hikingBoot: '🥾',
  flatShoe: '🥿',
  highHeeledShoe: '👠',
  womansSandal: '👡',
  balletShoes: '🩰',
  womansBoot: '👢',
  crown: '👑',
  womansHat: '👒',
  topHat: '🎩',
  graduationCap: '🎓',
  billedCap: '🧢',
  rescueWorkersHelmet: '⛑',
  lipstick: '💄',
  ring: '💍',
  briefcase: '💼',
};

export default clothingAndAccessories;
